In [2]:
import numpy as np

#1D array
array=np.arange(1,21)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
# To find the sum
sum=np.sum(array)
print(sum)

210


In [4]:
#To find the mean
mean=np.mean(array)
print(mean)

10.5


In [5]:
#To find the median
median=np.median(array)
print(median)

10.5


In [6]:
#To find the standard deviation
deviation=np.std(array)
print(deviation)

5.766281297335398


In [7]:
#Indices where the number is grater than the 10
np.where(array>10)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)

In [9]:
# For the 4*4 dimension
array2=np.arange(1,17).reshape(4,4)
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
# To find the transpose
transpose=array2.T
print(transpose)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [12]:
# Row wise sum
sum1=np.sum(array2,axis=1)
print(sum1)

[10 26 42 58]


In [13]:
# Column wise sum
sum2=np.sum(array2,axis=0)
print(sum2)

[28 32 36 40]


In [14]:
# Random 3*3 
array3=np.random.randint(1,18,(3,3))
array4=np.random.randint(1,18,(3,3))
print("First array")
print(array3)
print("Second array")
print(array4)

First array
[[ 2 13 12]
 [ 3 14  3]
 [15 14 11]]
Second array
[[ 8  3  1]
 [ 8  2  9]
 [14 15  8]]


In [17]:
# Random operations on the array3 and array4
print(array3+array4)
print(" ")
print(array3-array4)
print(" ")
print(array3*array4)

[[10 16 13]
 [11 16 12]
 [29 29 19]]
 
[[-6 10 11]
 [-5 12 -6]
 [ 1 -1  3]]
 
[[ 16  39  12]
 [ 24  28  27]
 [210 210  88]]


In [18]:
# Dot product
print(np.dot(array3,array4))

[[288 212 215]
 [178  82 153]
 [386 238 229]]


In [19]:
# Reshape
array5=np.arange(1,13)
array5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
array6=array5.reshape(3,4)
print(array6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
array6[:2, -2:]

array([[3, 4],
       [7, 8]])